#!/bin/bash
# NOTE: This must be run with bash and not sh.

# This script creates a tgz backup of the whole project.

#COPY_TO=~/host/Dropbox/Backups/ufo-c
COPY_TO=~/host

rm -f list-of-files
find src -name '*.cpp'        >> list-of-files
find src -name '*.h'          >> list-of-files
find test -name '*.cpp'       >> list-of-files
find test -name '*.h'         >> list-of-files
find doc-local -name '*.txt'  >> list-of-files
ls script/*                   >> list-of-files
ls CMakeLists.txt             >> list-of-files

DESC="-$1"
if [ "-$1-" == "--" ]; then
  DESC=""
fi
NAME=`date +'%y%m%d-%H%M'${DESC}`.tgz
echo ${NAME}
tar --exclude=*~ -zcf .backups/${NAME} -T list-of-files

if [ -d "$COPY_TO" ]
then
    cp .backups/${NAME} $COPY_TO
else
    echo "Not copying to $COPY_TO"
fi
